---

- name: install nginx
  apt: pkg=nginx state=installed

- name: disable default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: start nginx on boot
  service: name=nginx enabled=yes 

- name: create ssl key directory
  file: path=/etc/nginx/ssl state=directory

- name: upload ssl config include
  copy: src=ssl-config dest=/etc/nginx/ssl/config
  notify: reload nginx
