---

- name: install nginx
  apt: pkg=nginx state=present

- name: disable default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: create ssl key directory
  file: path=/etc/nginx/ssl state=directory

- name: upload ssl config include
  copy: src=ssl-config dest=/etc/nginx/ssl/config
  notify: reload nginx

- name: configure nginx
  copy: src=config dest=/etc/nginx/conf.d/config.conf
  notify: reload nginx
