---

- name: install git
  apt: pkg=git state=installed

- name: install nodejs
  apt: pkg=nodejs state=installed

- name: install nodejs-legacy
  apt: pkg=nodejs-legacy state=installed

- name: install npm
  apt: pkg=npm state=installed

- name: install grunt-cli
  npm: name=grunt-cli global=yes

- name: checkout repo
  git: repo=ssh://sync.tomwadley.net:/mnt/vol/syncthing/tom-git/meadgame.git dest=~/git/saunter version=origin/longpath
  notify: reload nginx

- name: install dependencies
  command: npm install chdir=~/git/saunter

- name: build 
  command: grunt clean prod --map=longpathSmall.json chdir=~/git/saunter

- name: create web root
  file: path=/srv/saunter state=directory

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/saunter/build/ /srv/saunter/
  changed_when: False

- name: configure nginx site
  copy: src=nginx-site dest=/etc/nginx/sites-available/saunter
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/saunter dest=/etc/nginx/sites-enabled/saunter state=link
  notify: reload nginx

