---

- name: trust nodejs repo
  shell: wget -qO - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

- name: setup nodejs repo
  apt_repository: repo="deb https://deb.nodesource.com/node_8.x stretch main" update_cache=true

- name: install nodejs
  apt: pkg=nodejs state=present
