---

- name: install git
  apt: pkg=git state=installed

- name: install nodejs
  apt: pkg=nodejs state=installed

- name: install nodejs-legacy
  apt: pkg=nodejs-legacy state=installed

- name: install npm
  apt: pkg=npm state=installed

- name: install grunt-cli
  npm: name=grunt-cli global=yes

- name: checkout repo
  git: repo=ssh://sync.tomwadley.net:/mnt/vol/syncthing/tom-git/meadgame.git dest=~/git/saunter-thirty version=origin/12o-thirty
  notify: reload nginx

- name: install dependencies
  command: npm install chdir=~/git/saunter-thirty

- name: build 
  command: grunt clean prod chdir=~/git/saunter-thirty

- name: create web root
  file: path=/srv/saunter-thirty state=directory

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/saunter-thirty/build/ /srv/saunter-thirty/
  changed_when: False

- name: configure nginx site
  copy: src=nginx-site dest=/etc/nginx/sites-available/saunter-thirty
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/saunter-thirty dest=/etc/nginx/sites-enabled/saunter-thirty state=link
  notify: reload nginx

