---

- name: install git
  apt: pkg=git state=installed

- name: install ruby-bundler
  apt: pkg=ruby-bundler state=installed

- name: put horner.tomwadley.net in known_hosts
  lineinfile: dest=~/.ssh/known_hosts line="{{ lookup('file', 'known_hosts/horner.tomwadley.net') }}" create=true

- name: checkout repo
  git: repo=ssh://tom@horner.tomwadley.net:/mnt/storage/tom/git/tomwadley.net.git dest=~/git/tomwadley.net version=origin/master
  notify: reload nginx

- name: install gems
  command: bundle install chdir=~/git/tomwadley.net

- name: build site
  command: bundle exec jekyll build chdir=~/git/tomwadley.net

- name: create web root
  file: path=/srv/tomwadley.net state=directory

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/tomwadley.net/_site/ /srv/tomwadley.net/
  changed_when: False

- name: configure nginx site
  copy: src=nginx-site dest=/etc/nginx/sites-available/tomwadley.net
  notify: reload nginx

- name: upload ssl cert bundle
  copy: src=tomwadley.net.bundle.crt dest=/etc/nginx/ssl/tomwadley.net.bundle.crt mode=0600
  notify: reload nginx

- name: decrypt ssl private key
  include_vars: ssl_private_key.yml

- name: upload ssl private key
  copy: content="{{ ssl_private_key }}" dest=/etc/nginx/ssl/tomwadley.net.key mode=0600
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/tomwadley.net dest=/etc/nginx/sites-enabled/tomwadley.net state=link
  notify: reload nginx

