---

- name: install git
  apt: pkg=git state=installed

- name: install ruby-bundler
  apt: pkg=ruby-bundler state=installed

- name: put rosawadley.com in known_hosts
  lineinfile: dest=~/.ssh/known_hosts line="{{ lookup('file', 'known_hosts/rosawadley.com') }}" create=true

- name: put github.com in known_hosts
  lineinfile: dest=~/.ssh/known_hosts line="{{ lookup('file', 'known_hosts/github.com') }}" create=true

- name: checkout repo
  git: repo=ssh://tom@rosawadley.com:/mnt/storage/tom/git/tomwadley.net.git dest=~/git/tomwadley.net version=origin/master
  notify: reload nginx

- name: install gems
  command: bundle install chdir=~/git/tomwadley.net

- name: build site
  command: bundle exec jekyll build chdir=~/git/tomwadley.net

- name: create web root
  file: path=/srv/tomwadley.net state=directory

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/tomwadley.net/_site/ /srv/tomwadley.net/
  changed_when: False

- name: configure nginx site
  copy: src=nginx-site dest=/etc/nginx/sites-available/tomwadley.net
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/tomwadley.net dest=/etc/nginx/sites-enabled/tomwadley.net state=link
  notify: reload nginx

