---

- name: install git
  apt: pkg=git state=present

- name: install build-essential
  apt: pkg=build-essential state=present

- name: install ruby-dev
  apt: pkg=ruby-dev state=present

- name: install ruby-bundler
  apt: pkg=ruby-bundler state=present

- name: checkout repo
  git: repo=ssh://go@horner.tomwadley.net:/mnt/storage/tom/git/tomwadley.net.git dest=~/git/tomwadley.net version={{ revision }}
  notify: reload nginx

- name: install gems
  command: bundle install --deployment chdir=~/git/tomwadley.net

- name: build site
  command: bundle exec jekyll build chdir=~/git/tomwadley.net

- name: create web root
  file: path=/srv/tomwadley.net state=directory

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/tomwadley.net/_site/ /srv/tomwadley.net/
  changed_when: False

- name: configure nginx site
  copy: src=nginx-site dest=/etc/nginx/sites-available/tomwadley.net
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/tomwadley.net dest=/etc/nginx/sites-enabled/tomwadley.net state=link
  notify: reload nginx

