---

- name: install nginx
  apt: pkg=nginx state=installed

- name: install git
  apt: pkg=git state=installed

- name: put rosawadley.com in known_hosts
  lineinfile: dest=~/.ssh/known_hosts line="{{ lookup('file', 'known_hosts/rosawadley.com') }}" create=true

- name: put github.com in known_hosts
  lineinfile: dest=~/.ssh/known_hosts line="{{ lookup('file', 'known_hosts/github.com') }}" create=true

- name: checkout repo
  git: repo=ssh://tom@rosawadley.com:/mnt/storage/tom/git/classic.tomwadley.net.git dest=~/git/classic.tomwadley.net version=origin/master
  notify: reload nginx

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/classic.tomwadley.net /srv
  changed_when: False

- name: configure nginx site
  copy: src=nginx-site dest=/etc/nginx/sites-available/classic.tomwadley.net
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/classic.tomwadley.net dest=/etc/nginx/sites-enabled/classic.tomwadley.net state=link
  notify: reload nginx

- name: disable default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: start nginx on boot
  service: name=nginx enabled=yes 

