---

- name: install git
  apt: pkg=git state=installed

- name: checkout repo
  git: repo=ssh://tom@horner.tomwadley.net:/mnt/storage/tom/git/{{ repo_name }}.git dest=~/git/{{ repo_name }} version=origin/master
  notify: reload nginx

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/{{ repo_name }} /srv
  changed_when: False

- name: configure nginx site
  template: src=nginx-site dest=/etc/nginx/sites-available/{{ repo_name }}
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/{{ repo_name }} dest=/etc/nginx/sites-enabled/{{ repo_name }} state=link
  notify: reload nginx

