---

- name: disable ssh password auth
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication " insertafter="^#PasswordAuthentication " line="PasswordAuthentication no"
  notify: restart ssh

- name: install ufw
  apt: pkg=ufw state=present

- name: allow ssh
  ufw: rule=allow port=22 proto=tcp

- name: allow www
  ufw: rule=allow port=80 proto=tcp

- name: allow secure www
  ufw: rule=allow port=443 proto=tcp

- name: disallow everything else 
  ufw: state=enabled policy=deny

- name: install unattended-upgrades
  apt: pkg=unattended-upgrades state=present
  notify: run unattended upgrade

- name: enable auto reboot when required
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp='^(//)?Unattended-Upgrade::Automatic-Reboot ' line='Unattended-Upgrade::Automatic-Reboot "true";'
  notify: run unattended upgrade
