---

- name: update all packages
  apt: upgrade=dist update_cache=yes
  notify: reboot if required

- name: disable ssh password auth
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication " line="PasswordAuthentication no" state="present"
  notify: restart ssh

- name: allow ssh
  ufw: rule=allow port=22 proto=tcp

- name: allow www
  ufw: rule=allow port=80 proto=tcp

- name: allow secure www
  ufw: rule=allow port=443 proto=tcp

- name: disallow everything else 
  ufw: state=enabled policy=deny

- name: install unattended-upgrades
  apt: pkg=unattended-upgrades state=installed

- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic

- name: enable auto reboot when required
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp='^(//)?Unattended-Upgrade::Automatic-Reboot ' line='Unattended-Upgrade::Automatic-Reboot "true";'

- name: set auto reboot time
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp='^(//)?Unattended-Upgrade::Automatic-Reboot-Time ' line='Unattended-Upgrade::Automatic-Reboot-Time "02:00";'

- name: enable normal updates in addition to security updates
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp='^(//)?\s*"\${distro_id}:\${distro_codename}-updates";' line='{{'\t'}}"${distro_id}:${distro_codename}-updates";'
