---

- name: decrypt root password
  include_vars: mysql_root_password.yml

- debconf: name=mysql-server question='mysql-server/root_password' value={{ mysql_root_password }} vtype='password'
  changed_when: False
- debconf: name=mysql-server question='mysql-server/root_password_again' value={{ mysql_root_password }} vtype='password'
  changed_when: False

- name: install mysql-server
  apt: name=mysql-server state=present

- name: copy mysql config
  copy: src=my.cnf dest=/etc/mysql/conf.d/my.cnf
  notify: reload mysql

- name: start mysql on boot
  service: name=mysql enabled=yes 

