---

- debug: msg="Importing Wordpress site '{{ site_name }}'"
- debug: msg="wp_dbdump = {{ wp_dbdump | default(\"not defined - no database will be imported\") }}"
- debug: msg="wp_tarball = {{ wp_tarball | default(\"not defined - no wordpress tarball will be extracted\") }}"

- name: install php modules required by wordpress
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-mysql
    - php5-curl
    - php5-mcrypt
    - php5-gd

- name: install python-mysqldb for mysql_db module
  apt: pkg=python-mysqldb state=installed

- name: create web root
  file: path=/srv/{{ host_name }} state=directory

- include: import_dbdump.yml
  when: wp_dbdump is defined
  notify: reload php-fpm

- include: extract_tarball.yml
  when: wp_tarball is defined
  notify: reload php-fpm

- name: configure php-fpm pool
  template: src=php-fpm.conf dest=/etc/php5/fpm/pool.d/{{ host_name }}.conf
  notify: reload php-fpm

- name: configure nginx site
  template: src=nginx-site dest=/etc/nginx/sites-available/{{ host_name }}
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/{{ host_name }} dest=/etc/nginx/sites-enabled/{{ host_name }} state=link
  notify: reload nginx

