---

- name: install git
  apt: pkg=git state=installed

- name: install ruby
  apt: pkg=ruby state=installed

- name: put github.com in known_hosts
  lineinfile: dest=~/.ssh/known_hosts line="{{ lookup('file', 'known_hosts/github.com') }}" create=true

- name: checkout repo
  git: repo=https://github.com/rosan/rosanussbaum.com dest=~/git/{{ site_name }} version={{ revision }}
  notify: reload nginx

- name: install jekyll
  command: gem install jekyll -v 2.5.3 chdir=~/git/{{ site_name }}

- name: build site
  command: jekyll build chdir=~/git/{{ site_name }}

- name: create web root
  file: path=/srv/{{ site_name }} state=directory

- name: copy files to web root
  command: rsync -a --delete --exclude='.*' ~/git/{{ site_name }}/_site/ /srv/{{ site_name }}/
  changed_when: False

- name: configure nginx site
  template: src=nginx-site dest=/etc/nginx/sites-available/{{ site_name }}
  notify: reload nginx

- name: enable nginx site
  file: src=/etc/nginx/sites-available/{{ site_name }} dest=/etc/nginx/sites-enabled/{{ site_name }} state=link
  notify: reload nginx

